name: Dart CI & Docker Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Setup Dart SDK
      - uses: dart-lang/setup-dart@v1

      # Install dependencies
      - name: Install dependencies
        working-directory: journal/journalFrontend/journal_app
        run: dart pub get

      # Analyze code
      - name: Analyze project source
        working-directory: journal/journalFrontend/journal_app
        run: dart analyze

      # Run tests
      - name: Run tests
        working-directory: journal/journalFrontend/journal_app
        run: dart test

      # Log in to Docker Hub (only runs if tests pass)
      - name: Log in to Docker Hub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Docker image (tag with commit SHA and latest)
      - name: Build Docker image
        if: success()
        working-directory: journal/journalFrontend/journal_app
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/journal-app:${{ github.sha }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/journal-app:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/journal-app:latest

      # Push Docker image
      - name: Push Docker image
        if: success()
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/journal-app:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/journal-app:latest
